name: bball_blast
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  characters: ^1.3.0
  flame: ^1.17.0
  flame_forge2d: ^0.18.0
  flame_noise: ^0.3.2+1
  flutter:
    sdk: flutter
  path: ^1.9.0
  sqflite: ^2.3.3+1
  xml: ^6.5.0
  flame_audio: ^2.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/skyBackground/
    - assets/images/oceanBg/
    - assets/images/spaceBg/
    - assets/audio/
  fonts:
    - family: Score
      fonts: 
        - asset: assets/fonts/score.ttf
  shaders:
    - assets/shaders/animatedGradient.frag
    - assets/shaders/colorChange.frag